# Generated by Django 5.1.4 on 2025-01-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profileIFC',
            new_name='username_IFC',
        ),
    ]
