# Generated by Django 5.1.4 on 2025-01-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profileifc_user_username_ifc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='awards',
        ),
    ]
