# Generated by Django 5.1.4 on 2025-01-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pilotaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='type',
            field=models.CharField(choices=[('Tour', 'Tour')], default='Tour', max_length=5),
        ),
    ]
