# Generated by Django 5.1.4 on 2025-01-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_award_date_create_award_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='date_create',
            new_name='end_date',
        ),
    ]
