# Generated by Django 5.1.4 on 2025-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_date_create_award_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
