# Generated by Django 5.1.4 on 2025-01-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_end_date_award_date_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='date_create',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='award',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
